* My Emacs config

This repository has been around for a long time, and pretty much any change I
make I commit and push. I use Emacs on Windows, Linux, and Android, sometimes
on macOS, too. So that's where those different settings come from.

This document will be outdated soon, but let's write something down for now.

In general, I try to stick to built-in features if I can. I have replaced
lsp-mode with eglot as the latter matured, I have started using use-package,
icomplete, xref, speedbar over el-get, ido, hydra, treemacs ... over the years
as it evolves. I am not religious about it, I just like sharing config over
different platforms and sticking to built-in things makes that easier.

I am not religious about vanilla Emacs though, and there are some things I'm
still holding out on. =term= has gotten very good in Emacs 31, even TUIs such =btm=
work, but it's still not great on Windows, so I stick to =ghostel= for now. =vc= is
getting better, but it has nothing on =magit= for me. And =company-mode= is only
barely better for me these days than vertical =icomplete= an in-buffer
completions, but the integration with eglot documentation still makes it win
out for me... So there.

** Initial Setup

On most platforms, I set everything up using [[https://mise.jdx.dev/][mise]] and starting from my
[[https://github.com/timfel/dotfiles][dotfiles]], but that doesn't work on Android.

So on Android, I install Nextcloud, Unexpected Keyboard, and [[https://github.com/timfel/emacs-builder/releases][Emacs]] and [[https://github.com/timfel/emacs-builder/releases][Termux]].

First, I open Termux once, then close it.

Then I open Emacs, go to a scratch buffer, paste and eval this:

#+begin_src elisp
  (progn
    (unless (file-expand-wildcards "/sdcard/Download/")
      (x-popup-dialog t '("Allow storage access" ("Ok" . t)))
      (android-request-storage-access))
    (unless (file-expand-wildcards "/content/storage/com.termux.documents/")
      (x-popup-dialog t '("Choose the top-level Termux folder" ("Ok" . t)))
      (android-request-directory-access))
    (unless (file-expand-wildcards "/content/storage/org.nextcloud.documents/")
      (x-popup-dialog t '("Choose the top-level Nextcloud folder" ("Ok" . t)))
      (android-request-directory-access))
    (let ((termuxpath "/data/data/com.termux/files/usr/bin"))
      (setenv "PATH" (concat (getenv "PATH") ":"  termuxpath))
      (add-to-list 'exec-path termuxpath t))
    (when (executable-find "pkg")
      (shell-command "pkg update -yy")
      (shell-command "pkg upgrade -yy")
      (shell-command "pkg install -yy git gh mise")
      (shell-command "git clone https://github.com/timfel/dotfiles ~/dotfiles")
      (shell-command "mise trust ~/dotfiles")
      (shell-command "mise bootstrap apply --cd ~/dotfiles --force --yes")
      (delete-directory "~/.emacs.d" t)
      (shell-command "git clone https://github.com/timfel/.emacs.d ~/.emacs.d")
      (kill-emacs)))
#+end_src

Then start again.
